version: '2'
services:
  app:
    image: fair-api:latest
    container_name: fair-api
    ports:
      - 8062:8062
    environment:
      PORT: 8062
      ENV: local
      FAIR_API_DB_HOST: fair-api-db
      FAIR_API_DB_PORT: 5433
      FAIR_API_DB_NAME: fair-api
      FAIR_API_DB_USER: admin
      FAIR_API_DB_PASS: admin
  db:
    image: postgres:13-alpine
    container_name: fair-api-db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASS=admin
      - POSTGRES_DBNAME=fair-api
    volumes:
      - fair-api-volume:/var/lib/postgresql
volumes:
  fair-api-volume:
    driver: local
